source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'StarterApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StarterApp

pod 'GoogleMaps', '7.0.0'
pod 'Google-Maps-iOS-Utils', '4.1.0'

end
