# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenWeatherDemoProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenWeatherDemoProject
pod 'Alamofire', '~> 5.4'


end
