# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'EduTemplate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EduTemplate
  pod 'Alamofire'
  pod 'AlamofireNetworkActivityIndicator'

end
