# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DailyChallenge_20220821' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DailyChallenge_20220821
pod 'MaterialComponents/BottomSheet'
  target 'DailyChallenge_20220821Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DailyChallenge_20220821UITests' do
    # Pods for testing
  end

end
