# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TemplateExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TemplateExample

pod 'Alamofire'

  target 'TemplateExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TemplateExampleUITests' do
    # Pods for testing
  end

end
