# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DailyChallenge_20220822' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DailyChallenge_20220822
pod 'MaterialComponents/BottomSheet'

  target 'DailyChallenge_20220822Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DailyChallenge_20220822UITests' do
    # Pods for testing
  end

end
