# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MangoClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MangoClone
	
pod 'Hero'
pod 'lottie-ios'
pod 'XLPagerTabStrip', '~> 9.0'
pod 'Alamofire'
pod 'SnapKit', '~> 5.6.0'

  target 'MangoCloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MangoCloneUITests' do
    # Pods for testing
  end

end
