# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PodsTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PodsTest

  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'SwiftyJSON', '~> 2.3'

  target 'PodsTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PodsTestUITests' do
    # Pods for testing
  end

end


