# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenWeatherProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for OpenWeatherProject

pod 'Alamofire'

  target 'OpenWeatherProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenWeatherProjectUITests' do
    # Pods for testing
  end

end

